### ISSUE TITLE
GEDPRO não abre no IE

### ISSUE THREAD

**Issue by nadameu** [nadameu/ferramentaseproc#3]

**Comment by danielquadros** [comment]
Só complementando a descrição dessa demanda... possivelmente o problema está associado à nova versão do Mozilla Firefox (ESR 52.5.3 (32-bit)) disponibilizada aqui na rede da JFPR. O redirecionamento do Firefox para o IE, a partir do botão "Gedpro" no eProc, não está funcionando. Situação reportada por vários usuários a partir de hoje (08/jan/17).
