### ISSUE TITLE
Recurso "Agendar lançamento de evento"

### ISSUE THREAD

**Issue by danielquadros** [nadameu/ferramentaseproc#5]
Com o complemento habilitado no Firefox 52 ESR, ao criar uma minuta e tentar usar o recurso de "Agendar lançamento de evento/troca de localizaodr", a caixa de seleção "Evento a ser lançado:" fica oculta (só aparece o Listar Todos). Ao desativar o complemento, o recurso normaliza.

**Comment by nadameu** [comment]
Corrigido na versão 1.1.0.
